import React from "react";
export const data = [
  {
    id: 1,
    Word: "AN",
    Target: "Female",
    Weight: 0,
  },
  {
    id: 2,
    Word: "Aaron",
    Target: "Female",
    Weight: 0,
  },
  {
    id: 3,
    Word: "Abbey",
    Target: "Female",
    Weight: 0,
  },
  {
    id: 4,
    Word: "Abbotsford",
    Target: "Female",
    Weight: 0,
  },
  {
    id: 5,
    Word: "Abdul",
    Target: "Female",
    Weight: 0,
  },
  {
    id: 6,
    Word: "Abdullah",
    Target: "Female",
    Weight: 0,
  },
  {
    id: 7,
    Word: "AbdurRahman",
    Target: "Female",
    Weight: 0,
  },
  {
    id: 8,
    Word: "Abell",
    Target: "Female",
    Weight: 0,
  },
  {
    id: 9,
    Word: "Abells",
    Target: "Female",
    Weight: 0,
  },
  {
    id: 10,
    Word: "Abloom",
    Target: "Female",
    Weight: 0,
  },
  // {
  //   id: 11,
  //   Word: "Aboulela",
  //   Target: "Female",
  //   Weight: 4,
  // },
  // {
  //   id: 12,
  //   Word: "Aboulelas",
  //   Target: "Female",
  //   Weight: 1,
  // },
  // {
  //   id: 13,
  //   Word: "Absalom",
  //   Target: "Female",
  //   Weight: 0,
  // },
  // {
  //   id: 14,
  //   Word: "Academy",
  //   Target: "Female",
  //   Weight: 0,
  // },
  // {
  //   id: 15,
  //   Word: "Accepting",
  //   Target: "Female",
  //   Weight: 1,
  // },
  // {
  //   id: 16,
  //   Word: "Accidental",
  //   Target: "Female",
  //   Weight: 0,
  // },
  // {
  //   id: 17,
  //   Word: "According",
  //   Target: "Female",
  //   Weight: 1,
  // },
  // {
  //   id: 18,
  //   Word: "Accordingly",
  //   Target: "Female",
  //   Weight: 1,
  // },
  // {
  //   id: 19,
  //   Word: "Account",
  //   Target: "Female",
  //   Weight: 0,
  // },
  // {
  //   id: 20,
  //   Word: "Accounting",
  //   Target: "Female",
  //   Weight: 0,
  // },
  // {
  //   id: 21,
  //   Word: "Achebe",
  //   Target: "Female",
  //   Weight: 0,
  // },
  // {
  //   id: 22,
  //   Word: "Achebes",
  //   Target: "Female",
  //   Weight: 0,
  // },
  // {
  //   id: 23,
  //   Word: "Achille",
  //   Target: "Female",
  //   Weight: 0,
  // },
  // {
  //   id: 24,
  //   Word: "Acquaintance",
  //   Target: "Female",
  //   Weight: 0,
  // },
  // {
  //   id: 25,
  //   Word: "Across",
  //   Target: "Female",
  //   Weight: 0,
  // },
  // {
  //   id: 26,
  //   Word: "Act",
  //   Target: "Female",
  //   Weight: 0,
  // },
  // {
  //   id: 27,
  //   Word: "Acts",
  //   Target: "Female",
  //   Weight: 1,
  // },
  // {
  //   id: 28,
  //   Word: "Adam",
  //   Target: "Female",
  //   Weight: 0,
  // },
  // {
  //   id: 29,
  //   Word: "AdamBede",
  //   Target: "Female",
  //   Weight: 0,
  // },
  // {
  //   id: 30,
  //   Word: "Adams",
  //   Target: "Female",
  //   Weight: 0,
  // },
  // {
  //   id: 31,
  //   Word: "Adapting",
  //   Target: "Female",
  //   Weight: 1,
  // },
  // {
  //   id: 32,
  //   Word: "Adichie",
  //   Target: "Female",
  //   Weight: 0,
  // },
  // {
  //   id: 33,
  //   Word: "Adichies",
  //   Target: "Female",
  //   Weight: 0,
  // },
  // {
  //   id: 34,
  //   Word: "Admittedly",
  //   Target: "Female",
  //   Weight: 0,
  // },
  // {
  //   id: 35,
  //   Word: "Adomo",
  //   Target: "Female",
  //   Weight: 0,
  // },
  // {
  //   id: 36,
  //   Word: "Adorn",
  //   Target: "Female",
  //   Weight: 0,
  // },
  // {
  //   id: 37,
  //   Word: "Adorno",
  //   Target: "Female",
  //   Weight: 0,
  // },
  // {
  //   id: 38,
  //   Word: "Adventures",
  //   Target: "Female",
  //   Weight: 0,
  // },
  // {
  //   id: 39,
  //   Word: "Aesthetic",
  //   Target: "Female",
  //   Weight: 0,
  // },
  // {
  //   id: 40,
  //   Word: "Aesthetics",
  //   Target: "Female",
  //   Weight: 0,
  // },
  // {
  //   id: 41,
  //   Word: "Affecting",
  //   Target: "Female",
  //   Weight: 0,
  // },
  // {
  //   id: 42,
  //   Word: "Affective",
  //   Target: "Female",
  //   Weight: 0,
  // },
  // {
  //   id: 43,
  //   Word: "Africa",
  //   Target: "Female",
  //   Weight: 1,
  // },
  // {
  //   id: 44,
  //   Word: "African",
  //   Target: "Female",
  //   Weight: 3,
  // },
  // {
  //   id: 45,
  //   Word: "Africans",
  //   Target: "Female",
  //   Weight: 0,
  // },
  // {
  //   id: 46,
  //   Word: "After",
  //   Target: "Female",
  //   Weight: 0,
  // },
  // {
  //   id: 47,
  //   Word: "Afterlives",
  //   Target: "Female",
  //   Weight: 0,
  // },
  // {
  //   id: 48,
  //   Word: "Against",
  //   Target: "Female",
  //   Weight: 0,
  // },
  // {
  //   id: 49,
  //   Word: "Agamben",
  //   Target: "Female",
  //   Weight: 0,
  // },
];
